/**
 * phoneTimezone.js
 * Derives an IANA timezone from a WhatsApp phone number's country-dialling prefix.
 * Longest-prefix match is used so 254 beats 25.
 */

const PHONE_TIMEZONE_MAP = {
  // ── North America ──────────────────────────────────────────────
  '1':   'America/New_York',
  // ── Russia / Central Asia ──────────────────────────────────────
  '7':   'Europe/Moscow',
  // ── Africa ─────────────────────────────────────────────────────
  '20':  'Africa/Cairo',
  '27':  'Africa/Johannesburg',
  '212': 'Africa/Casablanca',
  '213': 'Africa/Algiers',
  '216': 'Africa/Tunis',
  '218': 'Africa/Tripoli',
  '220': 'Africa/Banjul',
  '221': 'Africa/Dakar',
  '222': 'Africa/Nouakchott',
  '223': 'Africa/Bamako',
  '224': 'Africa/Conakry',
  '225': 'Africa/Abidjan',
  '226': 'Africa/Ouagadougou',
  '227': 'Africa/Niamey',
  '228': 'Africa/Lome',
  '229': 'Africa/Porto-Novo',
  '230': 'Indian/Mauritius',
  '231': 'Africa/Monrovia',
  '232': 'Africa/Freetown',
  '233': 'Africa/Accra',
  '234': 'Africa/Lagos',
  '235': 'Africa/Ndjamena',
  '236': 'Africa/Bangui',
  '237': 'Africa/Douala',
  '238': 'Atlantic/Cape_Verde',
  '239': 'Africa/Sao_Tome',
  '240': 'Africa/Malabo',
  '241': 'Africa/Libreville',
  '242': 'Africa/Brazzaville',
  '243': 'Africa/Kinshasa',
  '244': 'Africa/Luanda',
  '245': 'Africa/Bissau',
  '246': 'Indian/Chagos',
  '248': 'Indian/Mahe',
  '249': 'Africa/Khartoum',
  '250': 'Africa/Kigali',
  '251': 'Africa/Addis_Ababa',
  '252': 'Africa/Mogadishu',
  '253': 'Africa/Djibouti',
  '254': 'Africa/Nairobi',
  '255': 'Africa/Dar_es_Salaam',
  '256': 'Africa/Kampala',
  '257': 'Africa/Bujumbura',
  '258': 'Africa/Maputo',
  '260': 'Africa/Lusaka',
  '261': 'Indian/Antananarivo',
  '262': 'Indian/Reunion',
  '263': 'Africa/Harare',
  '264': 'Africa/Windhoek',
  '265': 'Africa/Blantyre',
  '266': 'Africa/Maseru',
  '267': 'Africa/Gaborone',
  '268': 'Africa/Mbabane',
  '269': 'Indian/Comoro',
  '290': 'Atlantic/St_Helena',
  '291': 'Africa/Asmara',
  // ── Europe ─────────────────────────────────────────────────────
  '30':  'Europe/Athens',
  '31':  'Europe/Amsterdam',
  '32':  'Europe/Brussels',
  '33':  'Europe/Paris',
  '34':  'Europe/Madrid',
  '36':  'Europe/Budapest',
  '39':  'Europe/Rome',
  '40':  'Europe/Bucharest',
  '41':  'Europe/Zurich',
  '43':  'Europe/Vienna',
  '44':  'Europe/London',
  '45':  'Europe/Copenhagen',
  '46':  'Europe/Stockholm',
  '47':  'Europe/Oslo',
  '48':  'Europe/Warsaw',
  '49':  'Europe/Berlin',
  '297': 'America/Aruba',
  '298': 'Atlantic/Faroe',
  '299': 'America/Godthab',
  '350': 'Europe/Gibraltar',
  '351': 'Europe/Lisbon',
  '352': 'Europe/Luxembourg',
  '353': 'Europe/Dublin',
  '354': 'Atlantic/Reykjavik',
  '355': 'Europe/Tirane',
  '356': 'Europe/Malta',
  '357': 'Asia/Nicosia',
  '358': 'Europe/Helsinki',
  '359': 'Europe/Sofia',
  '370': 'Europe/Vilnius',
  '371': 'Europe/Riga',
  '372': 'Europe/Tallinn',
  '373': 'Europe/Chisinau',
  '374': 'Asia/Yerevan',
  '375': 'Europe/Minsk',
  '376': 'Europe/Andorra',
  '377': 'Europe/Monaco',
  '380': 'Europe/Kiev',
  '381': 'Europe/Belgrade',
  '382': 'Europe/Podgorica',
  '385': 'Europe/Zagreb',
  '386': 'Europe/Ljubljana',
  '387': 'Europe/Sarajevo',
  '389': 'Europe/Skopje',
  '420': 'Europe/Prague',
  '421': 'Europe/Bratislava',
  '423': 'Europe/Vaduz',
  // ── South America ──────────────────────────────────────────────
  '51':  'America/Lima',
  '52':  'America/Mexico_City',
  '53':  'America/Havana',
  '54':  'America/Argentina/Buenos_Aires',
  '55':  'America/Sao_Paulo',
  '56':  'America/Santiago',
  '57':  'America/Bogota',
  '58':  'America/Caracas',
  '500': 'Atlantic/Stanley',
  '501': 'America/Belize',
  '502': 'America/Guatemala',
  '503': 'America/El_Salvador',
  '504': 'America/Tegucigalpa',
  '505': 'America/Managua',
  '506': 'America/Costa_Rica',
  '507': 'America/Panama',
  '508': 'America/Miquelon',
  '509': 'America/Port-au-Prince',
  '590': 'America/Guadeloupe',
  '591': 'America/La_Paz',
  '592': 'America/Guyana',
  '593': 'America/Guayaquil',
  '594': 'America/Cayenne',
  '595': 'America/Asuncion',
  '596': 'America/Martinique',
  '597': 'America/Paramaribo',
  '598': 'America/Montevideo',
  '599': 'America/Curacao',
  // ── Asia / Pacific ─────────────────────────────────────────────
  '60':  'Asia/Kuala_Lumpur',
  '61':  'Australia/Sydney',
  '62':  'Asia/Jakarta',
  '63':  'Asia/Manila',
  '64':  'Pacific/Auckland',
  '65':  'Asia/Singapore',
  '66':  'Asia/Bangkok',
  '670': 'Asia/Dili',
  '673': 'Asia/Brunei',
  '674': 'Pacific/Nauru',
  '675': 'Pacific/Port_Moresby',
  '676': 'Pacific/Tongatapu',
  '677': 'Pacific/Guadalcanal',
  '678': 'Pacific/Efate',
  '679': 'Pacific/Fiji',
  '680': 'Pacific/Palau',
  '681': 'Pacific/Wallis',
  '682': 'Pacific/Rarotonga',
  '683': 'Pacific/Niue',
  '685': 'Pacific/Apia',
  '686': 'Pacific/Tarawa',
  '687': 'Pacific/Noumea',
  '688': 'Pacific/Funafuti',
  '689': 'Pacific/Gambier',
  '691': 'Pacific/Pohnpei',
  '692': 'Pacific/Majuro',
  '81':  'Asia/Tokyo',
  '82':  'Asia/Seoul',
  '84':  'Asia/Ho_Chi_Minh',
  '86':  'Asia/Shanghai',
  '850': 'Asia/Pyongyang',
  '852': 'Asia/Hong_Kong',
  '853': 'Asia/Macau',
  '855': 'Asia/Phnom_Penh',
  '856': 'Asia/Vientiane',
  '880': 'Asia/Dhaka',
  '886': 'Asia/Taipei',
  '90':  'Europe/Istanbul',
  '91':  'Asia/Kolkata',
  '92':  'Asia/Karachi',
  '93':  'Asia/Kabul',
  '94':  'Asia/Colombo',
  '95':  'Asia/Rangoon',
  '960': 'Indian/Maldives',
  '961': 'Asia/Beirut',
  '962': 'Asia/Amman',
  '963': 'Asia/Damascus',
  '964': 'Asia/Baghdad',
  '965': 'Asia/Kuwait',
  '966': 'Asia/Riyadh',
  '967': 'Asia/Aden',
  '968': 'Asia/Muscat',
  '970': 'Asia/Gaza',
  '971': 'Asia/Dubai',
  '972': 'Asia/Jerusalem',
  '973': 'Asia/Bahrain',
  '974': 'Asia/Qatar',
  '975': 'Asia/Thimphu',
  '976': 'Asia/Ulaanbaatar',
  '977': 'Asia/Kathmandu',
  '92':  'Asia/Karachi',
  '992': 'Asia/Dushanbe',
  '993': 'Asia/Ashgabat',
  '994': 'Asia/Baku',
  '995': 'Asia/Tbilisi',
  '996': 'Asia/Bishkek',
  '998': 'Asia/Tashkent',
  '98':  'Asia/Tehran',
};

/**
 * Extract raw digits from a WhatsApp JID.
 * Works for both "2547130@s.whatsapp.net" and bare "2547130" strings.
 * @param {string} jid
 * @returns {string} digits only
 */
function extractPhone(jid) {
  if (!jid) return '';
  return jid.split('@')[0].replace(/\D/g, '');
}

/**
 * Return the IANA timezone that best matches the given WhatsApp JID/number.
 * Uses longest-prefix matching so country codes like 254 beat 25 or 2.
 * Falls back to 'UTC' if no match is found.
 * @param {string} jidOrPhone  e.g. "254713046497@s.whatsapp.net" or "254713046497"
 * @returns {string} IANA timezone string
 */
function getTimezoneFromPhone(jidOrPhone) {
  const digits = extractPhone(jidOrPhone);
  if (!digits) return 'UTC';

  for (let len = Math.min(digits.length, 4); len >= 1; len--) {
    const prefix = digits.slice(0, len);
    if (PHONE_TIMEZONE_MAP[prefix]) {
      return PHONE_TIMEZONE_MAP[prefix];
    }
  }
  return 'UTC';
}

export { getTimezoneFromPhone };
